Console.WriteLine("Cidades-Litoral-sul");
Console.WriteLine("");

Console.WriteLine("Peruíbe");
Console.WriteLine("Iaanhaém");
Console.WriteLine("Ilha Compria");
Console.WriteLine("Iguape");
Console.WriteLine("Mongaguá");
Console.WriteLine("Cananéia");
Console.WriteLine("Praia Grande");
Console.WriteLine("Registro");
Console.WriteLine("Sete Barras");
Console.WriteLine("Eldorado");
Console.WriteLine("Pedro de Toledo");
Console.WriteLine("Juquiá");
Console.WriteLine("Pariquera-Açu");
Console.WriteLine ("Cajati");
Console.WriteLine("Itariri");
Console.WriteLine("Miracatu");
Console.WriteLine("jacupiranga");
